version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
  kafka_mongodb:
    image: mongo
    container_name: kafka_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: kafkadb
    volumes:
      - kafka_mongo_init:/docker-entrypoint-initdb.d
      - kafka_mongo_data:/data/db
volumes:
  zookeeper_data:
    driver: local
    driver_opts:
      type: none
      device: ./docker/zookeeper
      o: bind
  kafka_data:
    driver: local
    driver_opts:
      type: none
      device: ./docker/kafka
      o: bind
  kafka_mongo_init:
    driver: local
    driver_opts:
      type: none
      device: ./docker/mongodb/init
      o: bind
  kafka_mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./docker/mongodb/data
      o: bind
